name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/dummy-image:latest
          context: .
          file: Dockerfile

      - name: SSH Command to Pull and Run Docker Image
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Pull the latest image from Docker Hub
            docker pull ${{ vars.DOCKER_USERNAME }}/dummy-image:latest
            
            # Stop and remove the existing container if it exists
            docker stop my_container_name || true
            docker rm my_container_name || true
            
            # Run the new container
            docker run -d --name my_container_name -p 80:80 ${{ vars.DOCKER_USERNAME }}/dummy-image:latest
